%/****************************************************************************/
%/****************************************************************************/
%/* (C) Copyright 2020 2021 Devise Electronics Pvt Ltd.                      */
%/* File Name: deMCD_types.m                                                  */
%/* Author: deVCU-deMCD Generated                                                   */
%/* Status: Draft Version                                                    */
%/****************************************************************************/
%/****************************************************************************/

function aDbcEnumAvailable = deMCD_types_dbc()


aDbcEnumAvailable = {};


Simulink.defineIntEnumType('Tras_Current_Range_t', ... 
{'ReverseLED','ParkLED','NeutralLED','DriveLED'}, ... 
[82;80;78;68],...
'Description', 'enum for signal Tras_Current_Range', ...
'DefaultValue', 'ReverseLED', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Tras_Current_Range_t'];


Simulink.defineIntEnumType('B2T_BMS_Work_Mode_t', ... 
{'Description_for_the_value__0x1_','Discharge_Mode'}, ... 
[1;0],...
'Description', 'enum for signal B2T_BMS_Work_Mode', ...
'DefaultValue', 'Description_for_the_value__0x1_', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'B2T_BMS_Work_Mode_t'];


Simulink.defineIntEnumType('B2T_Comp_Speed_Restriction_t', ... 
{'Comp_Restriction_to_off','Comp_Restriction_to_30Hz','Comp_Restriction_to_45Hz','No_Restriction'}, ... 
[3;2;1;0],...
'Description', 'enum for signal B2T_Comp_Speed_Restriction', ...
'DefaultValue', 'Comp_Restriction_to_off', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'B2T_Comp_Speed_Restriction_t'];


Simulink.defineIntEnumType('B2T_TMS_Control_CMD_t', ... 
{'Self_Circulation','Warm','Cooling','Standby'}, ... 
[3;2;1;0],...
'Description', 'enum for signal B2T_TMS_Control_CMD', ...
'DefaultValue', 'Self_Circulation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'B2T_TMS_Control_CMD_t'];


Simulink.defineIntEnumType('B2T_Mode_t', ... 
{'According_VCU','According_TMS'}, ... 
[1;0],...
'Description', 'enum for signal B2T_Mode', ...
'DefaultValue', 'According_VCU', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'B2T_Mode_t'];


Simulink.defineIntEnumType('Acc_Pedal2KickdownSwitch_t', ... 
{'KickdownActive','KickdownPassive'}, ... 
[1;0],...
'Description', 'enum for signal Acc_Pedal2KickdownSwitch', ...
'DefaultValue', 'KickdownActive', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Acc_Pedal2KickdownSwitch_t'];


Simulink.defineIntEnumType('Acc_Pedal1LowIdleSwitch_t', ... 
{'LowIdle_Condition','Not_LowIdle_Condition'}, ... 
[1;0],...
'Description', 'enum for signal Acc_Pedal1LowIdleSwitch', ...
'DefaultValue', 'LowIdle_Condition', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Acc_Pedal1LowIdleSwitch_t'];


Simulink.defineIntEnumType('Host_BMSStateRequest_t', ... 
{'Charge','DiagMode3','clear_fault_Mode','DiagMode1','Fault_Shutdown','Discharge','Ready','Sleep'}, ... 
[7;6;5;4;3;2;1;0],...
'Description', 'enum for signal Host_BMSStateRequest', ...
'DefaultValue', 'Charge', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Host_BMSStateRequest_t'];


Simulink.defineIntEnumType('BMS_Tmin_SubPack_ID_t', ... 
{'SubPack_8','SubPack_7','SubPack_6','SubPack_5','SubPack_4','SubPack_3','SubPack_2','SubPack_1'}, ... 
[7;6;5;4;3;2;1;0],...
'Description', 'enum for signal BMS_Tmin_SubPack_ID', ...
'DefaultValue', 'SubPack_8', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_Tmin_SubPack_ID_t'];


Simulink.defineIntEnumType('BMS_Tmax_SubPack_ID_t', ... 
{'SubPack_8','SubPack_7','SubPack_6','SubPack_5','SubPack_4','SubPack_3','SubPack_2','SubPack_1'}, ... 
[7;6;5;4;3;2;1;0],...
'Description', 'enum for signal BMS_Tmax_SubPack_ID', ...
'DefaultValue', 'SubPack_8', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_Tmax_SubPack_ID_t'];


Simulink.defineIntEnumType('Subpack5_DTC_t', ... 
{'BMS_SysChrgOverCurrentFault','BMS_SysChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentFault','BMS_SysHallSensorFault','BMS_CellOVFault','BMS_CellOVWarning','BMS_CellUVWarning','BMS_CellUVFault','BMS_CellVoltDeltaNoLoadFault','BMS_CellVoltDeltaNoLoadWarning','BMS_CellVoltDeltaWithLoadWarning','BMS_CellVoltDeltaWithLoadFault','BMS_CellOTFault','BMS_CellOTWarning','BMS_CellUTWarning','BMS_CellUTFault','BMS_CellTempDeltaWarning','BMS_CellTempDeltaFault','BMS_CellTSenseCircuitFault','BMS_CANMessageCounterFault','BMS_CANChecksumFault','BMS_CANMasterMuteFault','BMS_AmbientTempHighFault','BMS_AmbientTempHighWarning','BMS_AmbientTempLowFault','BMS_AmbientTempLowWarning','BMS_ChargeCompleteWarning','BMS_DischargeCompleteWarning','BMS_EEPROM_HW_Fault','BMS_HighTempCharge','BMS_HighTempDischarge','BMS_LidOpenFault','BMS_LowTempCharge','BMS_LowTempDischarge','BMS_PackBalancingWarning','BMS_SysAuxVIN_OVFault','BMS_SysAuxVIN_UVFault','BMS_SysHVILFault','BMS_SysPrechargeFault','BMS_SysRISOFault','BMS_VoltageMismatchFault','BMS_WeldedContactorFault','BMS_StringFault','BMS_SubPackMuteFault','BMS_SubPackMuteWarning','BMS_SubPackOVFault','BMS_SubPackOVWarning','BMS_SubPackUVFault','BMS_SubPackUVWarning','BMS_SubPackVSenseCircuitFault','Nofault'}, ... 
[64;65;66;67;68;80;81;82;83;84;85;86;87;96;97;98;99;100;101;103;160;161;162;164;165;166;167;168;171;172;173;174;175;176;177;178;179;180;181;182;183;185;186;196;204;206;207;208;209;210;211;0],...
'Description', 'enum for signal Subpack5_DTC', ...
'DefaultValue', 'BMS_SysChrgOverCurrentFault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Subpack5_DTC_t'];


Simulink.defineIntEnumType('Subpack4_DTC_t', ... 
{'BMS_SysChrgOverCurrentFault','BMS_SysChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentFault','BMS_SysHallSensorFault','BMS_CellOVFault','BMS_CellOVWarning','BMS_CellUVWarning','BMS_CellUVFault','BMS_CellVoltDeltaNoLoadFault','BMS_CellVoltDeltaNoLoadWarning','BMS_CellVoltDeltaWithLoadWarning','BMS_CellVoltDeltaWithLoadFault','BMS_CellOTFault','BMS_CellOTWarning','BMS_CellUTWarning','BMS_CellUTFault','BMS_CellTempDeltaWarning','BMS_CellTempDeltaFault','BMS_CellTSenseCircuitFault','BMS_CANMessageCounterFault','BMS_CANChecksumFault','BMS_CANMasterMuteFault','BMS_AmbientTempHighFault','BMS_AmbientTempHighWarning','BMS_AmbientTempLowFault','BMS_AmbientTempLowWarning','BMS_ChargeCompleteWarning','BMS_DischargeCompleteWarning','BMS_EEPROM_HW_Fault','BMS_HighTempCharge','BMS_HighTempDischarge','BMS_LidOpenFault','BMS_LowTempCharge','BMS_LowTempDischarge','BMS_PackBalancingWarning','BMS_SysAuxVIN_OVFault','BMS_SysAuxVIN_UVFault','BMS_SysHVILFault','BMS_SysPrechargeFault','BMS_SysRISOFault','BMS_VoltageMismatchFault','BMS_WeldedContactorFault','BMS_StringFault','BMS_SubPackMuteFault','BMS_SubPackMuteWarning','BMS_SubPackOVFault','BMS_SubPackOVWarning','BMS_SubPackUVFault','BMS_SubPackUVWarning','BMS_SubPackVSenseCircuitFault','Nofault'}, ... 
[64;65;66;67;68;80;81;82;83;84;85;86;87;96;97;98;99;100;101;103;160;161;162;164;165;166;167;168;171;172;173;174;175;176;177;178;179;180;181;182;183;185;186;196;204;206;207;208;209;210;211;0],...
'Description', 'enum for signal Subpack4_DTC', ...
'DefaultValue', 'BMS_SysChrgOverCurrentFault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Subpack4_DTC_t'];


Simulink.defineIntEnumType('Subpack3_DTC_t', ... 
{'BMS_SysChrgOverCurrentFault','BMS_SysChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentFault','BMS_SysHallSensorFault','BMS_CellOVFault','BMS_CellOVWarning','BMS_CellUVWarning','BMS_CellUVFault','BMS_CellVoltDeltaNoLoadFault','BMS_CellVoltDeltaNoLoadWarning','BMS_CellVoltDeltaWithLoadWarning','BMS_CellVoltDeltaWithLoadFault','BMS_CellOTFault','BMS_CellOTWarning','BMS_CellUTWarning','BMS_CellUTFault','BMS_CellTempDeltaWarning','BMS_CellTempDeltaFault','BMS_CellTSenseCircuitFault','BMS_CANMessageCounterFault','BMS_CANChecksumFault','BMS_CANMasterMuteFault','BMS_AmbientTempHighFault','BMS_AmbientTempHighWarning','BMS_AmbientTempLowFault','BMS_AmbientTempLowWarning','BMS_ChargeCompleteWarning','BMS_DischargeCompleteWarning','BMS_EEPROM_HW_Fault','BMS_HighTempCharge','BMS_HighTempDischarge','BMS_LidOpenFault','BMS_LowTempCharge','BMS_LowTempDischarge','BMS_PackBalancingWarning','BMS_SysAuxVIN_OVFault','BMS_SysAuxVIN_UVFault','BMS_SysHVILFault','BMS_SysPrechargeFault','BMS_SysRISOFault','BMS_VoltageMismatchFault','BMS_WeldedContactorFault','BMS_StringFault','BMS_SubPackMuteFault','BMS_SubPackMuteWarning','BMS_SubPackOVFault','BMS_SubPackOVWarning','BMS_SubPackUVFault','BMS_SubPackUVWarning','BMS_SubPackVSenseCircuitFault','Nofault'}, ... 
[64;65;66;67;68;80;81;82;83;84;85;86;87;96;97;98;99;100;101;103;160;161;162;164;165;166;167;168;171;172;173;174;175;176;177;178;179;180;181;182;183;185;186;196;204;206;207;208;209;210;211;0],...
'Description', 'enum for signal Subpack3_DTC', ...
'DefaultValue', 'BMS_SysChrgOverCurrentFault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Subpack3_DTC_t'];


Simulink.defineIntEnumType('Subpack2_DTC_t', ... 
{'BMS_SysChrgOverCurrentFault','BMS_SysChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentFault','BMS_SysHallSensorFault','BMS_CellOVFault','BMS_CellOVWarning','BMS_CellUVWarning','BMS_CellUVFault','BMS_CellVoltDeltaNoLoadFault','BMS_CellVoltDeltaNoLoadWarning','BMS_CellVoltDeltaWithLoadWarning','BMS_CellVoltDeltaWithLoadFault','BMS_CellOTFault','BMS_CellOTWarning','BMS_CellUTWarning','BMS_CellUTFault','BMS_CellTempDeltaWarning','BMS_CellTempDeltaFault','BMS_CellTSenseCircuitFault','BMS_CANMessageCounterFault','BMS_CANChecksumFault','BMS_CANMasterMuteFault','BMS_AmbientTempHighFault','BMS_AmbientTempHighWarning','BMS_AmbientTempLowFault','BMS_AmbientTempLowWarning','BMS_ChargeCompleteWarning','BMS_DischargeCompleteWarning','BMS_EEPROM_HW_Fault','BMS_HighTempCharge','BMS_HighTempDischarge','BMS_LidOpenFault','BMS_LowTempCharge','BMS_LowTempDischarge','BMS_PackBalancingWarning','BMS_SysAuxVIN_OVFault','BMS_SysAuxVIN_UVFault','BMS_SysHVILFault','BMS_SysPrechargeFault','BMS_SysRISOFault','BMS_VoltageMismatchFault','BMS_WeldedContactorFault','BMS_StringFault','BMS_SubPackMuteFault','BMS_SubPackMuteWarning','BMS_SubPackOVFault','BMS_SubPackOVWarning','BMS_SubPackUVFault','BMS_SubPackUVWarning','BMS_SubPackVSenseCircuitFault','Nofault'}, ... 
[64;65;66;67;68;80;81;82;83;84;85;86;87;96;97;98;99;100;101;103;160;161;162;164;165;166;167;168;171;172;173;174;175;176;177;178;179;180;181;182;183;185;186;196;204;206;207;208;209;210;211;0],...
'Description', 'enum for signal Subpack2_DTC', ...
'DefaultValue', 'BMS_SysChrgOverCurrentFault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Subpack2_DTC_t'];


Simulink.defineIntEnumType('Subpack1_DTC_t', ... 
{'BMS_SysChrgOverCurrentFault','BMS_SysChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentFault','BMS_SysHallSensorFault','BMS_CellOVFault','BMS_CellOVWarning','BMS_CellUVWarning','BMS_CellUVFault','BMS_CellVoltDeltaNoLoadFault','BMS_CellVoltDeltaNoLoadWarning','BMS_CellVoltDeltaWithLoadWarning','BMS_CellVoltDeltaWithLoadFault','BMS_CellOTFault','BMS_CellOTWarning','BMS_CellUTWarning','BMS_CellUTFault','BMS_CellTempDeltaWarning','BMS_CellTempDeltaFault','BMS_CellTSenseCircuitFault','BMS_CANMessageCounterFault','BMS_CANChecksumFault','BMS_CANMasterMuteFault','BMS_AmbientTempHighFault','BMS_AmbientTempHighWarning','BMS_AmbientTempLowFault','BMS_AmbientTempLowWarning','BMS_ChargeCompleteWarning','BMS_DischargeCompleteWarning','BMS_EEPROM_HW_Fault','BMS_HighTempCharge','BMS_HighTempDischarge','BMS_LidOpenFault','BMS_LowTempCharge','BMS_LowTempDischarge','BMS_PackBalancingWarning','BMS_SysAuxVIN_OVFault','BMS_SysAuxVIN_UVFault','BMS_SysHVILFault','BMS_SysPrechargeFault','BMS_SysRISOFault','BMS_VoltageMismatchFault','BMS_WeldedContactorFault','BMS_StringFault','BMS_SubPackMuteFault','BMS_SubPackMuteWarning','BMS_SubPackOVFault','BMS_SubPackOVWarning','BMS_SubPackUVFault','BMS_SubPackUVWarning','BMS_SubPackVSenseCircuitFault','Nofault'}, ... 
[64;65;66;67;68;80;81;82;83;84;85;86;87;96;97;98;99;100;101;103;160;161;162;164;165;166;167;168;171;172;173;174;175;176;177;178;179;180;181;182;183;185;186;196;204;206;207;208;209;210;211;0],...
'Description', 'enum for signal Subpack1_DTC', ...
'DefaultValue', 'BMS_SysChrgOverCurrentFault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Subpack1_DTC_t'];


Simulink.defineIntEnumType('Subpack0_DTC_t', ... 
{'BMS_SysChrgOverCurrentFault','BMS_SysChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentWarning','BMS_SysDisChrgOverCurrentFault','BMS_SysHallSensorFault','BMS_CellOVFault','BMS_CellOVWarning','BMS_CellUVWarning','BMS_CellUVFault','BMS_CellVoltDeltaNoLoadFault','BMS_CellVoltDeltaNoLoadWarning','BMS_CellVoltDeltaWithLoadWarning','BMS_CellVoltDeltaWithLoadFault','BMS_CellOTFault','BMS_CellOTWarning','BMS_CellUTWarning','BMS_CellUTFault','BMS_CellTempDeltaWarning','BMS_CellTempDeltaFault','BMS_CellTSenseCircuitFault','BMS_CANMessageCounterFault','BMS_CANChecksumFault','BMS_CANMasterMuteFault','BMS_AmbientTempHighFault','BMS_AmbientTempHighWarning','BMS_AmbientTempLowFault','BMS_AmbientTempLowWarning','BMS_ChargeCompleteWarning','BMS_DischargeCompleteWarning','BMS_EEPROM_HW_Fault','BMS_HighTempCharge','BMS_HighTempDischarge','BMS_LidOpenFault','BMS_LowTempCharge','BMS_LowTempDischarge','BMS_PackBalancingWarning','BMS_SysAuxVIN_OVFault','BMS_SysAuxVIN_UVFault','BMS_SysHVILFault','BMS_SysPrechargeFault','BMS_SysRISOFault','BMS_VoltageMismatchFault','BMS_WeldedContactorFault','BMS_StringFault','BMS_SubPackMuteFault','BMS_SubPackMuteWarning','BMS_SubPackOVFault','BMS_SubPackOVWarning','BMS_SubPackUVFault','BMS_SubPackUVWarning','BMS_SubPackVSenseCircuitFault','Nofault'}, ... 
[64;65;66;67;68;80;81;82;83;84;85;86;87;96;97;98;99;100;101;103;160;161;162;164;165;166;167;168;171;172;173;174;175;176;177;178;179;180;181;182;183;185;186;196;204;206;207;208;209;210;211;0],...
'Description', 'enum for signal Subpack0_DTC', ...
'DefaultValue', 'BMS_SysChrgOverCurrentFault', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Subpack0_DTC_t'];


Simulink.defineIntEnumType('BMS_BalanceStatus_t', ... 
{'Balance_Inactive','Balance_Active'}, ... 
[0;1],...
'Description', 'enum for signal BMS_BalanceStatus', ...
'DefaultValue', 'Balance_Inactive', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_BalanceStatus_t'];


Simulink.defineIntEnumType('BMS_RISOState_t', ... 
{'RISO_Off','RISO_On'}, ... 
[0;1],...
'Description', 'enum for signal BMS_RISOState', ...
'DefaultValue', 'RISO_Off', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_RISOState_t'];


Simulink.defineIntEnumType('HV_Contactor_Status_t', ... 
{'Contactor_Closed','Contactor_Open'}, ... 
[1;0],...
'Description', 'enum for signal HV_Contactor_Status', ...
'DefaultValue', 'Contactor_Closed', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'HV_Contactor_Status_t'];


Simulink.defineIntEnumType('BMS_SubPack16Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack16Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack16Status_t'];


Simulink.defineIntEnumType('BMS_SubPack15Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack15Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack15Status_t'];


Simulink.defineIntEnumType('BMS_SubPack14Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack14Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack14Status_t'];


Simulink.defineIntEnumType('BMS_SubPack13Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack13Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack13Status_t'];


Simulink.defineIntEnumType('BMS_SubPack12Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack12Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack12Status_t'];


Simulink.defineIntEnumType('BMS_SubPack11Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack11Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack11Status_t'];


Simulink.defineIntEnumType('BMS_SubPack10Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack10Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack10Status_t'];


Simulink.defineIntEnumType('BMS_SubPack9Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack9Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack9Status_t'];


Simulink.defineIntEnumType('BMS_SubPack8Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack8Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack8Status_t'];


Simulink.defineIntEnumType('BMS_SubPack7Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack7Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack7Status_t'];


Simulink.defineIntEnumType('BMS_SubPack6Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack6Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack6Status_t'];


Simulink.defineIntEnumType('BMS_SubPack5Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack5Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack5Status_t'];


Simulink.defineIntEnumType('BMS_SubPack4Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack4Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack4Status_t'];


Simulink.defineIntEnumType('BMS_SubPack3Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack3Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack3Status_t'];


Simulink.defineIntEnumType('BMS_SubPack2Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack2Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack2Status_t'];


Simulink.defineIntEnumType('BMS_SubPack1Status_t', ... 
{'Normal_Operation','Warning','Fault','Not_Populated'}, ... 
[0;1;2;3],...
'Description', 'enum for signal BMS_SubPack1Status', ...
'DefaultValue', 'Normal_Operation', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_SubPack1Status_t'];


Simulink.defineIntEnumType('BMS_PackState_t', ... 
{'Initialization','Sleep_','Wake_Up','Ready','Discharge_Active','Fault_Limp','Fault_Critical','DiagnosticMode1','DiagnosticMode2','DiagnosticMode3','Charge_Active'}, ... 
[0;1;2;3;4;5;6;7;8;9;10],...
'Description', 'enum for signal BMS_PackState', ...
'DefaultValue', 'Initialization', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_PackState_t'];


Simulink.defineIntEnumType('Sys_DTC_t', ... 
{'Charge_Complete','Imbalanced_String','Lost_COMM_with_VCU','Lost_COMM_with_Slaves','Mismatch_I','Mismatch_V','Lid_Open','Welded_Contactor','Riso_fault','precharge_fault','HVIL__JB_','Aux_Battery_Under_Voltage__UV_','Aux_Battery_Over_Voltage__OV_','NoFault'}, ... 
[236;235;234;233;232;231;230;229;228;227;226;225;224;0],...
'Description', 'enum for signal Sys_DTC', ...
'DefaultValue', 'Charge_Complete', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Sys_DTC_t'];


Simulink.defineIntEnumType('BMS_Vmin_SubPack_ID_t', ... 
{'SubPack_8','SubPack_7','SubPack_6','SubPack_5','SubPack_4','SubPack_3','SubPack_2','SubPack_1'}, ... 
[7;6;5;4;3;2;1;0],...
'Description', 'enum for signal BMS_Vmin_SubPack_ID', ...
'DefaultValue', 'SubPack_8', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_Vmin_SubPack_ID_t'];


Simulink.defineIntEnumType('BMS_Vmax_SubPack_ID_t', ... 
{'Description_for_the_value','SubPack_7','SubPack_6','SubPack_5','SubPack_4','SubPack_3','SubPack_2','SubPack_1'}, ... 
[7;6;5;4;3;2;1;0],...
'Description', 'enum for signal BMS_Vmax_SubPack_ID', ...
'DefaultValue', 'Description_for_the_value', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'BMS_Vmax_SubPack_ID_t'];


Simulink.defineIntEnumType('McuRequestId_t', ... 
{'McuMinDCVoltage','McuMaxDCVoltage','McuTotalMotorRotationUsingMcu','McuTotalMotorRotation','McuSwVersion2','McuSwVersion1','McuMaxMotorSpeed','McuMaxMotorTorque','McuProtocolVersion'}, ... 
[8;7;6;5;4;3;2;1;0],...
'Description', 'enum for signal McuRequestId', ...
'DefaultValue', 'McuMinDCVoltage', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'McuRequestId_t'];


Simulink.defineIntEnumType('HighPowerVoltageStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal HighPowerVoltageStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'HighPowerVoltageStatus_t'];


Simulink.defineIntEnumType('HighPowerCurrentStatus_t', ... 
{'Description_for_the_value__0x1_','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal HighPowerCurrentStatus', ...
'DefaultValue', 'Description_for_the_value__0x1_', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'HighPowerCurrentStatus_t'];


Simulink.defineIntEnumType('AuxiliaryVoltageStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal AuxiliaryVoltageStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'AuxiliaryVoltageStatus_t'];


Simulink.defineIntEnumType('FaultPhaseToChassisStatus_t', ... 
{'Signal_is_invalid_or_not_used','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal FaultPhaseToChassisStatus', ...
'DefaultValue', 'Signal_is_invalid_or_not_used', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultPhaseToChassisStatus_t'];


Simulink.defineIntEnumType('FaultInterlockMotorCableStatus_t', ... 
{'Signal_is_invalid_or_not_used','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal FaultInterlockMotorCableStatus', ...
'DefaultValue', 'Signal_is_invalid_or_not_used', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultInterlockMotorCableStatus_t'];


Simulink.defineIntEnumType('FaultInterlockBatteryCableStatus_t', ... 
{'Signal_is_invalid_or_not_used','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal FaultInterlockBatteryCableStatus', ...
'DefaultValue', 'Signal_is_invalid_or_not_used', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultInterlockBatteryCableStatus_t'];


Simulink.defineIntEnumType('FaultDriveCoverWasOpenedStatus_t', ... 
{'Signal_is_invalid_or_not_used','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal FaultDriveCoverWasOpenedStatus', ...
'DefaultValue', 'Signal_is_invalid_or_not_used', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultDriveCoverWasOpenedStatus_t'];


Simulink.defineIntEnumType('FaultDriveCoverWasOpened_t', ... 
{'If_signal_valid__fault_detected','If_signal_valid__no_fault'}, ... 
[1;0],...
'Description', 'enum for signal FaultDriveCoverWasOpened', ...
'DefaultValue', 'If_signal_valid__fault_detected', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultDriveCoverWasOpened_t'];


Simulink.defineIntEnumType('FaultInterlockMotorCable_t', ... 
{'If_signal_valid__fault_detected','If_signal_valid__no_fault'}, ... 
[1;0],...
'Description', 'enum for signal FaultInterlockMotorCable', ...
'DefaultValue', 'If_signal_valid__fault_detected', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultInterlockMotorCable_t'];


Simulink.defineIntEnumType('FaultInterlockBatteryCable_t', ... 
{'Description_for_the_value__0x1_','If_signal_valid__no_fault'}, ... 
[1;0],...
'Description', 'enum for signal FaultInterlockBatteryCable', ...
'DefaultValue', 'Description_for_the_value__0x1_', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultInterlockBatteryCable_t'];


Simulink.defineIntEnumType('FaultPhaseToChassis_t', ... 
{'If_signal_valid__fault_detected','If_signal_valid__no_fault'}, ... 
[1;0],...
'Description', 'enum for signal FaultPhaseToChassis', ...
'DefaultValue', 'If_signal_valid__fault_detected', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'FaultPhaseToChassis_t'];


Simulink.defineIntEnumType('ReferenceCommandMode_t', ... 
{'Speed_Control_Torque_Limit_Mode','DC_Voltage_Mode__VoltageCommand_','Speed_Mode__SpeedCommand_','Torque_Mode__TorqueCommand_'}, ... 
[4;3;2;1],...
'Description', 'enum for signal ReferenceCommandMode', ...
'DefaultValue', 'Speed_Control_Torque_Limit_Mode', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ReferenceCommandMode_t'];


Simulink.defineIntEnumType('CommandModeExt_t', ... 
{'ON','OFF'}, ... 
[1;0],...
'Description', 'enum for signal CommandModeExt', ...
'DefaultValue', 'ON', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CommandModeExt_t'];


Simulink.defineIntEnumType('TorqueCommandStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal TorqueCommandStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'TorqueCommandStatus_t'];


Simulink.defineIntEnumType('SpeedCommandStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal SpeedCommandStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'SpeedCommandStatus_t'];


Simulink.defineIntEnumType('CommandMode_VmuCmd2_t', ... 
{'DC_Voltage_Mode__VoltageCommand_','Speed_Mode__SpeedCommand_','Torque_Mode__TorqueCommand_'}, ... 
[3;2;1],...
'Description', 'enum for signal CommandMode_VmuCmd2', ...
'DefaultValue', 'DC_Voltage_Mode__VoltageCommand_', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CommandMode_VmuCmd2_t'];


Simulink.defineIntEnumType('OperationalMode_t', ... 
{'Ev___Gear_Shifting','Ev___Purely_electric','Generator___Voltage_regulation','Neutral___No_torque'}, ... 
[3;2;1;0],...
'Description', 'enum for signal OperationalMode', ...
'DefaultValue', 'Ev___Gear_Shifting', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'OperationalMode_t'];


Simulink.defineIntEnumType('Acknowledgement_t', ... 
{'Ack__Positive_','Nack__Negative_'}, ... 
[1;0],...
'Description', 'enum for signal Acknowledgement', ...
'DefaultValue', 'Ack__Positive_', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'Acknowledgement_t'];


Simulink.defineIntEnumType('VmuRequestId_t', ... 
{'VmuBootNumber__Power_up_number_'}, ... 
[0],...
'Description', 'enum for signal VmuRequestId', ...
'DefaultValue', 'VmuBootNumber__Power_up_number_', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'VmuRequestId_t'];


Simulink.defineIntEnumType('ThermalIndicatorStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal ThermalIndicatorStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'ThermalIndicatorStatus_t'];


Simulink.defineIntEnumType('TractionTorqueAvailStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_correct'}, ... 
[1;0],...
'Description', 'enum for signal TractionTorqueAvailStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'TractionTorqueAvailStatus_t'];


Simulink.defineIntEnumType('SpeedReductionRequest_t', ... 
{'Request_to_reduce_speed','No_request'}, ... 
[1;0],...
'Description', 'enum for signal SpeedReductionRequest', ...
'DefaultValue', 'Request_to_reduce_speed', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'SpeedReductionRequest_t'];


Simulink.defineIntEnumType('EmergencyStop_t', ... 
{'Emergency_stop_requested','System_OK'}, ... 
[1;0],...
'Description', 'enum for signal EmergencyStop', ...
'DefaultValue', 'Emergency_stop_requested', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'EmergencyStop_t'];


Simulink.defineIntEnumType('CommandMode_McuCmd1Res_t', ... 
{'Speed_Control_Torque_Limit_Mode','DC_Voltage_Mode__VoltageCommand_','Speed_Mode__SpeedCommand_','Torque_Mode__TorqueCommand_'}, ... 
[4;3;2;1],...
'Description', 'enum for signal CommandMode_McuCmd1Res', ...
'DefaultValue', 'Speed_Control_Torque_Limit_Mode', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'CommandMode_McuCmd1Res_t'];


Simulink.defineIntEnumType('MaxSafeMotorSpeedReverseStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal MaxSafeMotorSpeedReverseStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MaxSafeMotorSpeedReverseStatus_t'];


Simulink.defineIntEnumType('MaxSafeMotorSpeedForwardStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal MaxSafeMotorSpeedForwardStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MaxSafeMotorSpeedForwardStatus_t'];


Simulink.defineIntEnumType('OperationalMode_McuCmd1Res_t', ... 
{'Ev___Gear_Shifting','Ev___Purely_electric','Generator___Voltage_regulation','Neutral___No_torque'}, ... 
[3;2;1;0],...
'Description', 'enum for signal OperationalMode_McuCmd1Res', ...
'DefaultValue', 'Ev___Gear_Shifting', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'OperationalMode_McuCmd1Res_t'];


Simulink.defineIntEnumType('TractionDeratingStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal TractionDeratingStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'TractionDeratingStatus_t'];


Simulink.defineIntEnumType('StateMcu_t', ... 
{'WaitForSafeCondition','ReadyToShutdown','CloseDown','Failure','Operational','TearDown','Startup','Standby','Initialisation'}, ... 
[8;7;6;5;4;3;2;1;0],...
'Description', 'enum for signal StateMcu', ...
'DefaultValue', 'WaitForSafeCondition', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'StateMcu_t'];


Simulink.defineIntEnumType('MinBatteryVoltageStatus_t', ... 
{'Description_for_the_value__0x1_','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal MinBatteryVoltageStatus', ...
'DefaultValue', 'Description_for_the_value__0x1_', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MinBatteryVoltageStatus_t'];


Simulink.defineIntEnumType('MaxDischargeCurrentStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal MaxDischargeCurrentStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MaxDischargeCurrentStatus_t'];


Simulink.defineIntEnumType('MaxChargeCurrentStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal MaxChargeCurrentStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MaxChargeCurrentStatus_t'];


Simulink.defineIntEnumType('MaxBatteryVoltageStatus_t', ... 
{'Signal_associated_is_invalid','Signal_associated_is_valid'}, ... 
[1;0],...
'Description', 'enum for signal MaxBatteryVoltageStatus', ...
'DefaultValue', 'Signal_associated_is_invalid', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'MaxBatteryVoltageStatus_t'];


Simulink.defineIntEnumType('OperationRequest_VmuCmd1_t', ... 
{'ShutdownReq','OperationalReq','StandbyReq'}, ... 
[2;1;0],...
'Description', 'enum for signal OperationRequest_VmuCmd1', ...
'DefaultValue', 'ShutdownReq', ...
'AddClassNameToEnumNames', true);

aDbcEnumAvailable = [aDbcEnumAvailable; 'OperationRequest_VmuCmd1_t'];


end
