/*
***************************************************************************
***************************************************************************
(C) 2020 2021 Devise Electronics Pvt Ltd  All rights reserved.

All data and information contained in or disclosed by this document is
confidential and proprietary information of Devise Electronics Pvt Ltd and all
rights therein are expressly reserved.  By accepting this material the
recipient agrees that this material and the information contained therein
is held in confidence and in trust and will not be used, copied, reproduced
in whole or in part, nor its contents revealed in any manner to others
without the express written permission of Devise Electronics Pvt Ltd

Devise Electronics Pvt Ltd
Erandwane,
411038, Pune,
India

File Name: ecu_com_cfg_gen.h
Author: deVCU-deMCD Generated 
E-mail: devcu@deviseelectronics.com 
***************************************************************************
***************************************************************************
*/

#ifndef ECU_COM_CFG_GEN_H
#define ECU_COM_CFG_GEN_H


/*********** NETWORK 1 ***********/
/* Defines of Rx Messages */
#define ECU_COM_RX1_MSGS_NUM                                               (11)
#define REFU_DC_AC_TO_VCU_RX2                                              (0)
#define REFU_DC_AC_TO_VCU_RX1                                              (1)
#define BMS_TEMPERATURE                                                    (2)
#define BMS_SAFETY                                                         (3)
#define BMS_PACK_SUBPACK_STATUS                                            (4)
#define BMS_CHARGE_DISCHARGE_DETAILS                                       (5)
#define BMS_BATTERY_PARAMETERS                                             (6)
#define BMS_AVERAGECELL_TEMP                                               (7)
#define G2EVCC_VCU_RX2                                                     (8)
#define G2EVCC_VCU_RX1                                                     (9)
#define G1EVCC_VCU_RX2                                                     (10)


/* Defines of Tx Messages */
#define ECU_COM_TX1_MSGS_NUM                                               (9)
#define GPIO_CHECK_VCUTEST1                                                (0)
#define VCU_PARALOGGINGTX1                                                 (1)
#define VCU_TO_REFU_DC_AC                                                  (2)
#define HOST_REQUESTBMSMODE                                                (3)
#define G2VCU_EVCC_TX2                                                     (4)
#define G2VCU_EVCC_TX1                                                     (5)
#define G1VCU_EVCC_TX2                                                     (6)
#define G1VCU_EVCC_TX1                                                     (7)
#define GPIO_CHECK_VCUTEST2                                                (8)


/* Defines of Rx Signals */
#define ECU_COM_RX1_SIGNALS_NUM                                            (79)
#define OUTPUT_CURRENT_EHVS                                                (0)
#define OUTPUT_CURRENT_AIRCOMP                                             (1)
#define ACTUAL_TEMP_PUMP_AIRCOMP                                           (2)
#define FAULT_CODE_EHVS_VCU_RX                                             (3)
#define DC_LINK_VOLTAGE_VCU_RX                                             (4)
#define STATUSU1_FAULT_AIRCOMP_VCU_RX                                      (5)
#define STATUSU0_FAULT_EHVS_VCU_RX                                         (6)
#define STATUSU0_WARNING_EHVS_VCU_RX                                       (7)
#define STATUSU0_OVERCURRENTFAULT_EHVS_V                                   (8)
#define STATUSU1_WARNING_AIRCOMP_VCU_RX                                    (9)
#define STATUSU1_OVERTEMP_AIRCOMP_VCU_RX                                   (10)
#define STATUSU1_OVERCURRENT_AIRCOMP_VCU                                   (11)
#define BMS_HIGHESTOUTLETTEMP                                              (12)
#define BMS_HIGHESTINLETTEMP                                               (13)
#define BMS_TMIN_CELL_ID                                                   (14)
#define BMS_TMAX_CELL_ID                                                   (15)
#define BMS_TMIN_SUBPACK_ID                                                (16)
#define BMS_TMAX_SUBPACK_ID                                                (17)
#define BMS_MINCELLTEMP                                                    (18)
#define BMS_MAXCELLTEMP                                                    (19)
#define CHECKSUM_123                                                       (20)
#define HV_CONTACTOR_STATUS                                                (21)
#define SWITCHING_SYNC_STATUS                                              (22)
#define BMS_SYSTEMISORES                                                   (23)
#define BMS_DCBUSVOLTAGE                                                   (24)
#define BMS_SUBPACK16STATUS                                                (25)
#define BMS_SUBPACK15STATUS                                                (26)
#define BMS_SUBPACK14STATUS                                                (27)
#define BMS_SUBPACK13STATUS                                                (28)
#define BMS_SUBPACK12STATUS                                                (29)
#define BMS_SUBPACK11STATUS                                                (30)
#define BMS_SUBPACK10STATUS                                                (31)
#define BMS_SUBPACK9STATUS                                                 (32)
#define BMS_SUBPACK8STATUS                                                 (33)
#define BMS_SUBPACK7STATUS                                                 (34)
#define BMS_SUBPACK6STATUS                                                 (35)
#define BMS_SUBPACK5STATUS                                                 (36)
#define BMS_SUBPACK4STATUS                                                 (37)
#define BMS_SUBPACK3STATUS                                                 (38)
#define BMS_SUBPACK2STATUS                                                 (39)
#define BMS_SUBPACK1STATUS                                                 (40)
#define DETECTED_STRING                                                    (41)
#define CONNECTED_STRING                                                   (42)
#define BMS_PACKSTATE                                                      (43)
#define SYS_DTC                                                            (44)
#define BMS_MAXBATVOLTALLOWED                                              (45)
#define BMS_MAXCONTCHRGCURRENT                                             (46)
#define BMS_MAXCONTDISCHRGCURRENT                                          (47)
#define MESSAGECOUNTER_122                                                 (48)
#define CHECKSUM_122                                                       (49)
#define BATTERY_SOH                                                        (50)
#define BMS_SOC                                                            (51)
#define BMS_PACKVOLTAGE                                                    (52)
#define BMS_MESSAGECOUNTER_126_HEARTBEAT                                   (53)
#define BMS_PACKCURRENT                                                    (54)
#define BMS_CHECKSUM_126                                                   (55)
#define BMS_AVERAGECELLTEMPERATURE                                         (56)
#define BMS_AVERAGECELLVOLTAGE                                             (57)
#define G2_GUNLOCKFEEDBACK                                                 (58)
#define G2VEHICLE_IMMOBILIZE                                               (59)
#define G2GUN_LOCK_FAULT                                                   (60)
#define G2TEMPERATURE2_FAULT                                               (61)
#define G2TEMPERATURE1_FAULT                                               (62)
#define G2TEMPERATURE_2_VAL                                                (63)
#define G2TEMPERATURE_1_VAL                                                (64)
#define G2DIFF_CURRENT_MEASURE                                             (65)
#define G2NEGATIVE_CONTACTOR_CONTROL                                       (66)
#define G2CHARGING_STATUS                                                  (67)
#define G2POSITIVE_CONTACTOR_CONTROL                                       (68)
#define G2CHARGER_GUN_DETECTED                                             (69)
#define G2EVCC_READY                                                       (70)
#define G2EVCC_STATUS_CODE                                                 (71)
#define G1_GUNLOCKFEEDBACK                                                 (72)
#define G1VEHICLE_IMMOBILIZE                                               (73)
#define G1GUN_LOCK_FAULT                                                   (74)
#define G1TEMPERATURE2_FAULT                                               (75)
#define G1TEMPERATURE1_FAULT                                               (76)
#define G1TEMPERATURE_2_VAL                                                (77)
#define G1TEMPERATURE_1_VAL                                                (78)


/* Defines of Tx Signals */
#define ECU_COM_TX1_SIGNALS_NUM                                            (64)
#define P08                                                                (0)
#define P35                                                                (1)
#define P36                                                                (2)
#define P38                                                                (3)
#define P52                                                                (4)
#define P53                                                                (5)
#define P54                                                                (6)
#define P55                                                                (7)
#define P61                                                                (8)
#define P11                                                                (9)
#define P12                                                                (10)
#define P13                                                                (11)
#define P25                                                                (12)
#define P27                                                                (13)
#define P28                                                                (14)
#define P29                                                                (15)
#define P30                                                                (16)
#define P32                                                                (17)
#define ANL_P48                                                            (18)
#define ANL_P49_24V                                                        (19)
#define P07                                                                (20)
#define ANL_P50_24V                                                        (21)
#define ANL_P65_12V                                                        (22)
#define ANL_P67_5V                                                         (23)
#define VCU_PARALOGCOOLENTOUT                                              (24)
#define VCU_PARALOGCOOLENTIN                                               (25)
#define VCU_PARALOG_MOTORRPM                                               (26)
#define VCU_PARALOG_VEHSPEED                                               (27)
#define VCU_PARALOG_TRQCMD                                                 (28)
#define VCU_PARALOG_ACCPEDAL                                               (29)
#define DCDCONOFF                                                          (30)
#define CONTROL1_AIRCOMP                                                   (31)
#define CONTROL0_EHPS                                                      (32)
#define REBOOT_REQUEST                                                     (33)
#define HOST_BMSSTATEREQUEST                                               (34)
#define MESSAGECOUNTER_200                                                 (35)
#define CHECKSUM_200                                                       (36)
#define G2NOMI_BATT_CAPA                                                   (37)
#define G2REMAIN_BATT_CAPA                                                 (38)
#define G2EV_ERROR_CODE                                                    (39)
#define G2VEHI_STOP_CHARG_FLAG                                             (40)
#define G2CHARG_COMP_FLAG                                                  (41)
#define G2EV_READY_FLAG                                                    (42)
#define G2BATTERY_PACK_PRESENT_VOLT                                        (43)
#define G2EV_CONTI_CHARG_CUR_LIMIT                                         (44)
#define G2SOC                                                              (45)
#define G2EV_MAX_CHARG_CUR_LIMIT                                           (46)
#define G1NOMI_BATT_CAPA                                                   (47)
#define G1REMAIN_BATT_CAPA                                                 (48)
#define G1EV_ERROR_CODE                                                    (49)
#define G1VEHI_STOP_CHARG_FLAG                                             (50)
#define G1CHARG_COMP_FLAG                                                  (51)
#define G1EV_READY_FLAG                                                    (52)
#define G1BATTERY_PACK_PRESENT_VOLT                                        (53)
#define G1EV_CONTI_CHARG_CUR_LIMIT                                         (54)
#define G1SOC                                                              (55)
#define G1EV_MAX_CHARG_CUR_LIMIT                                           (56)
#define INTERNAL_ANL_VCU_VTG                                               (57)
#define ANL_P68_5V                                                         (58)
#define ANL_P69_5V                                                         (59)
#define PWM_P66_DC                                                         (60)
#define PWM_P66_FREQ                                                       (61)
#define PWM_P56_FREQ                                                       (62)
#define PWM_P56_DC                                                         (63)


/*********** NETWORK 2 ***********/
/* Defines of Rx Messages */
#define ECU_COM_RX2_MSGS_NUM                                               (10)
#define TMS_VCU_RX1                                                        (0)
#define PUMPINFORMATION_RX                                                 (1)
#define MCUTHERMAL2                                                        (2)
#define MCUPOLLINGMCURESPONSE                                              (3)
#define MCUINFO1                                                           (4)
#define MCUEVENTINFO1                                                      (5)
#define MCUPOLLINGVMU                                                      (6)
#define MCUINFO2                                                           (7)
#define MCUCOMMAND2RESPONSE                                                (8)
#define MCUCOMMAND1RESPONSE                                                (9)


/* Defines of Tx Messages */
#define ECU_COM_TX2_MSGS_NUM                                               (8)
#define VCU_TMS_TX                                                         (0)
#define PUMPCONTROLINFORMATION_TX                                          (1)
#define VMUSELECTPROTOCOLVERSION                                           (2)
#define VMUPOLLINGMCU                                                      (3)
#define VMUCOMMANDSAFETY                                                   (4)
#define VMUCOMMAND2                                                        (5)
#define VMUPOLLINGVMURESPONSE                                              (6)
#define VMUCOMMAND1                                                        (7)


/* Defines of Rx Signals */
#define ECU_COM_RX2_SIGNALS_NUM                                            (82)
#define T2B_SIGNAL_LIFE                                                    (0)
#define T2B_FAULT_CODE                                                     (1)
#define T2B_COMP_FREQUENCY                                                 (2)
#define T2B_BMS_WORK_MODE                                                  (3)
#define T2B_TMS_WORK_MODE                                                  (4)
#define T2B_MODE                                                           (5)
#define T2B_COOLANT_OUT_TEMP                                               (6)
#define T2B_COOLANT_IN_TEMP                                                (7)
#define PUMPTEMP                                                           (8)
#define PUMPVOLTAGE                                                        (9)
#define PUMPUNDERVOLTAGEFAULT                                              (10)
#define PUMPTHERMALFAULT                                                   (11)
#define PUMPSTALLFAULT                                                     (12)
#define PUMPSPEED                                                          (13)
#define PUMPOVERVOLTAGEFAULT                                               (14)
#define PUMPOVERCURRENTFAULT                                               (15)
#define PUMPFAULTLEVEL                                                     (16)
#define PUMPDRYRUNFAULT                                                    (17)
#define PUMPCURRENT                                                        (18)
#define PUMPCOMMUNICATIONFAULT                                             (19)
#define MOTORTEMPERATURE                                                   (20)
#define EMITEMPERATURE                                                     (21)
#define MCUTEMPERATURE                                                     (22)
#define AMBIENTTEMPERATURE                                                 (23)
#define ROLLINGCOUNTER_MCUTHERMAL2                                         (24)
#define MCU_POLLING_MCU_BYTE8                                              (25)
#define MCU_POLLING_MCU_BYTE7                                              (26)
#define MCU_POLLING_MCU_BYTE6                                              (27)
#define MCU_POLLING_MCU_BYTE5                                              (28)
#define MCU_POLLING_MCU_BYTE4                                              (29)
#define MCU_POLLING_MCU_BYTE3                                              (30)
#define MCU_POLLING_MCU_BYTE2                                              (31)
#define MCU_POLLING_MCU_BYTE1                                              (32)
#define ROLLINGCOUNTER_MCUINFO1                                            (33)
#define HIGHPOWERVOLTAGESTATUS                                             (34)
#define HIGHPOWERVOLTAGE                                                   (35)
#define HIGHPOWERCURRENTSTATUS                                             (36)
#define HIGHPOWERCURRENT                                                   (37)
#define AUXILIARYVOLTAGESTATUS                                             (38)
#define AUXILIARYVOLTAGE                                                   (39)
#define FAULTPHASETOCHASSISSTATUS                                          (40)
#define FAULTINTERLOCKMOTORCABLESTATUS                                     (41)
#define FAULTINTERLOCKBATTERYCABLESTATUS                                   (42)
#define FAULTDRIVECOVERWASOPENEDSTATUS                                     (43)
#define FAULTDRIVECOVERWASOPENED                                           (44)
#define FAULTINTERLOCKMOTORCABLE                                           (45)
#define FAULTINTERLOCKBATTERYCABLE                                         (46)
#define FAULTPHASETOCHASSIS                                                (47)
#define MCUPOLLINGVMU_BYTE8                                                (48)
#define MCUPOLLINGVMU_BYTE7                                                (49)
#define MCUPOLLINGVMU_BYTE6                                                (50)
#define MCUPOLLINGVMU_BYTE5                                                (51)
#define MCUPOLLINGVMU_BYTE4                                                (52)
#define MCUPOLLINGVMU_BYTE3                                                (53)
#define MCUPOLLINGVMU_BYTE2                                                (54)
#define MCUPOLLINGVMU_BYTE1                                                (55)
#define ROLLINGCOUNTER_MCUINFO2                                            (56)
#define MOTORTORQUEESTIMATEDSTATUS                                         (57)
#define REGENTORQUEAVAILSTATUS                                             (58)
#define TRACTIONTORQUEAVAILSTATUS                                          (59)
#define REGENTORQUEAVAIL                                                   (60)
#define TRACTIONTORQUEAVAIL                                                (61)
#define MOTORTORQUEESTIMATED                                               (62)
#define SPEEDREDUCTIONREQUEST                                              (63)
#define EMERGENCYSTOP                                                      (64)
#define ROLLINGCOUNTER_MCUCMD2RESPONSE                                     (65)
#define MOTORANGLESTATUS                                                   (66)
#define MOTORSPEEDSTATUS                                                   (67)
#define MOTORANGLE                                                         (68)
#define MOTORSPEED                                                         (69)
#define COMMANDMODE_MCUCMD1RES                                             (70)
#define MAXSAFEMOTORSPEEDREVERSESTATUS                                     (71)
#define MAXSAFEMOTORSPEEDREVERSE                                           (72)
#define MAXSAFEMOTORSPEEDFORWARDSTATUS                                     (73)
#define MAXSAFEMOTORSPEEDFORWARD                                           (74)
#define REGENDERATINGSTATUS                                                (75)
#define OPERATIONALMODE_MCUCMD1RES                                         (76)
#define TRACTIONDERATINGSTATUS                                             (77)
#define ROLLINGCOUNTER_MCUCMD1RESPONSE                                     (78)
#define REGENDERATING                                                      (79)
#define TRACTIONDERATING                                                   (80)
#define STATEMCU                                                           (81)


/* Defines of Tx Signals */
#define ECU_COM_TX2_SIGNALS_NUM                                            (40)
#define B2T_BMS_WORK_MODE                                                  (0)
#define B2T_SIGNAL_LIFE                                                    (1)
#define B2T_BATTERY_AVG_TEMP                                               (2)
#define B2T_SET_TARGET_TEMP                                                (3)
#define B2T_COMP_SPEED_RESTRICTION                                         (4)
#define B2T_TMS_CONTROL_CMD                                                (5)
#define B2T_MODE                                                           (6)
#define B2T_DIFFERENTIAL2                                                  (7)
#define B2T_DIFFERENTIAL1                                                  (8)
#define B2T_TCELL_MIN                                                      (9)
#define B2T_TCELL_MAX                                                      (10)
#define TARGETVALUE                                                        (11)
#define MAJORMCUPROTOCOL                                                   (12)
#define MINORMCUPROTOCOL                                                   (13)
#define MCUREQUESTID                                                       (14)
#define ROLLINGCOUNTER_VMUCMDSAFETY                                        (15)
#define REFERENCECOMMANDMODE                                               (16)
#define REFERENCESPEEDCOMMAND                                              (17)
#define REFERENCETORQUECOMMAND                                             (18)
#define ROLLINGCOUNTER_VMUCMD2                                             (19)
#define SPEEDCOMMAND                                                       (20)
#define TORQUECOMMAND                                                      (21)
#define COMMANDMODEEXT                                                     (22)
#define TORQUECOMMANDSTATUS                                                (23)
#define SPEEDCOMMANDSTATUS                                                 (24)
#define COMMANDMODE_VMUCMD2                                                (25)
#define OPERATIONALMODE                                                    (26)
#define ACKNOWLEDGEMENT                                                    (27)
#define BOOTNUMBER                                                         (28)
#define VMUREQUESTID                                                       (29)
#define ROLLINGCOUNTER_VMUCMD1                                             (30)
#define MINBATTERYVOLTAGESTATUS                                            (31)
#define MAXDISCHARGECURRENTSTATUS                                          (32)
#define MAXCHARGECURRENTSTATUS                                             (33)
#define MAXBATTERYVOLTAGESTATUS                                            (34)
#define MINBATTERYVOLTAGE                                                  (35)
#define MAXBATTERYVOLTAGE                                                  (36)
#define MAXDISCHARGECURRENT                                                (37)
#define MAXCHARGECURRENT                                                   (38)
#define OPERATIONREQUEST_VMUCMD1                                           (39)


/*********** NETWORK 3 ***********/
/* Defines of Rx Messages */
#define ECU_COM_RX3_MSGS_NUM                                               (5)
#define ACC_PEDAL_FAULT_RX                                                 (0)
#define AIR1_EBC_VCU_RX                                                    (1)
#define ACC_PEDAL_POS_RX                                                   (2)
#define EBC1_EBC_VCU                                                       (3)
#define GEAR_SELECTOR_DNRP                                                 (4)


/* Defines of Tx Messages */
#define ECU_COM_TX3_MSGS_NUM                                               (2)
#define VCU_CFG_EM1_ER_TX                                                  (0)
#define VCU_CFG_EM1_BAM_TX                                                 (1)


/* Defines of Rx Signals */
#define ECU_COM_RX3_SIGNALS_NUM                                            (40)
#define ACC_PEDAL_FAULT_BYTE8                                              (0)
#define ACC_PEDAL_FAULT_BYTE7                                              (1)
#define ACC_PEDAL_FAULT_BYTE6                                              (2)
#define ACC_PEDAL_FAULT_BYTE5                                              (3)
#define ACC_PEDAL_FAULT_BYTE4                                              (4)
#define ACC_PEDAL_FAULT_BYTE3                                              (5)
#define ACC_PEDAL_FAULT_BYTE2                                              (6)
#define ACC_PEDAL_FAULT_BYTE1                                              (7)
#define AIR_COMPRESSOR_STATUS                                              (8)
#define AIR_SUSPENSION_SUPPLY_PRESSURE                                     (9)
#define AUXILIARY_EQUIPMENT_SUPPLY_PRESS                                   (10)
#define SERVICE_BRAKE_CIRCUIT_2_AIR_PRES                                   (11)
#define SERVICE_BRAKE_CIRCUIT_1_AIR_PRES                                   (12)
#define PARKING_AND_OR_TRAILER_AIR_PRESS                                   (13)
#define PNEUMATIC_SUPPLY_PRESSURE                                          (14)
#define ACCPEDAL_POS1                                                      (15)
#define ACC_PEDAL2KICKDOWNSWITCH                                           (16)
#define ACC_PEDAL1LOWIDLESWITCH                                            (17)
#define TRAILER_ABS_WARNING_SIGNAL                                         (18)
#define TRAILER_ABS_STATUS                                                 (19)
#define HALT_BRAKE_SWITCH                                                  (20)
#define SA_OF_CTRLLINGDEVICEFORBRAKECTRL                                   (21)
#define ATC_ASR_INFORMATION_SIGNAL                                         (22)
#define ABS_EBS_AMBER_WARNING_LAMP_STATE                                   (23)
#define EBS_RED_WARNING_LAMP_STATE                                         (24)
#define ABS_FULLY_OPERATIONAL                                              (25)
#define ENG_RET_SELECTION                                                  (26)
#define ACLTR_INTERLOCK_SWITCH                                             (27)
#define TRACTION_CTRL_OVR_SWITCH                                           (28)
#define ASR_HILL_HOLDER_SWITCH                                             (29)
#define ASR_OFFROAD_SWITCH                                                 (30)
#define ABS_OFFROAD_SWITCH                                                 (31)
#define BRAKE_PEDAL_POSITION                                               (32)
#define EBS_BRAKE_SWITCH                                                   (33)
#define ANTI_LOCK_BRAKING_ABS_ACTIVE                                       (34)
#define ASR_BRAKE_CTRL_ACTIVE                                              (35)
#define ASR_ENG_CTRL_ACTIVE                                                (36)
#define TRANSREQUEST_GEAR                                                  (37)
#define GEARSELECTOR_TESTSIG2                                              (38)
#define GEARSELECTOR_TESTSIG1                                              (39)


/* Defines of Tx Signals */
#define ECU_COM_TX3_SIGNALS_NUM                                            (10)
#define EM1_RET_LOCATION                                                   (0)
#define EM1_RET_TYPE                                                       (1)
#define EM1_REF_ENG_TORQ                                                   (2)
#define EM1_REF_RET_TORQ                                                   (3)
#define EM1_ER_SEQUENCE_NUMBER                                             (4)
#define TPCM_EM1_PGN                                                       (5)
#define TPCM_TPDT_5THFRAME                                                 (6)
#define TPCM_TPDT_FRAMES                                                   (7)
#define TPCM_EM1_BYT                                                       (8)
#define TPCM_EM1_BAM                                                       (9)




/* Defines of Application ECU Signals */

/* Defines of Application ECU Rx Signals */
#define ECU_COM_RX_SIGNALS_NUM                                             (201)
#define APP_RX_ABS_EBS_AMBER_WARNING_LAMP_STATE                            (0)
#define APP_RX_ABS_FULLY_OPERATIONAL                                       (1)
#define APP_RX_ABS_OFFROAD_SWITCH                                          (2)
#define APP_RX_ACCPEDAL_POS1                                               (3)
#define APP_RX_ACC_PEDAL1LOWIDLESWITCH                                     (4)
#define APP_RX_ACC_PEDAL2KICKDOWNSWITCH                                    (5)
#define APP_RX_ACC_PEDAL_FAULT_BYTE1                                       (6)
#define APP_RX_ACC_PEDAL_FAULT_BYTE2                                       (7)
#define APP_RX_ACC_PEDAL_FAULT_BYTE3                                       (8)
#define APP_RX_ACC_PEDAL_FAULT_BYTE4                                       (9)
#define APP_RX_ACC_PEDAL_FAULT_BYTE5                                       (10)
#define APP_RX_ACC_PEDAL_FAULT_BYTE6                                       (11)
#define APP_RX_ACC_PEDAL_FAULT_BYTE7                                       (12)
#define APP_RX_ACC_PEDAL_FAULT_BYTE8                                       (13)
#define APP_RX_ACLTR_INTERLOCK_SWITCH                                      (14)
#define APP_RX_ACTUAL_TEMP_PUMP_AIRCOMP                                    (15)
#define APP_RX_AIR_COMPRESSOR_STATUS                                       (16)
#define APP_RX_AIR_SUSPENSION_SUPPLY_PRESSURE                              (17)
#define APP_RX_AMBIENTTEMPERATURE                                          (18)
#define APP_RX_ANTI_LOCK_BRAKING_ABS_ACTIVE                                (19)
#define APP_RX_ASR_BRAKE_CTRL_ACTIVE                                       (20)
#define APP_RX_ASR_ENG_CTRL_ACTIVE                                         (21)
#define APP_RX_ASR_HILL_HOLDER_SWITCH                                      (22)
#define APP_RX_ASR_OFFROAD_SWITCH                                          (23)
#define APP_RX_ATC_ASR_INFORMATION_SIGNAL                                  (24)
#define APP_RX_AUXILIARYVOLTAGE                                            (25)
#define APP_RX_AUXILIARYVOLTAGESTATUS                                      (26)
#define APP_RX_AUXILIARY_EQUIPMENT_SUPPLY_PRESS                            (27)
#define APP_RX_BATTERY_SOH                                                 (28)
#define APP_RX_BMS_AVERAGECELLTEMPERATURE                                  (29)
#define APP_RX_BMS_AVERAGECELLVOLTAGE                                      (30)
#define APP_RX_BMS_CHECKSUM_126                                            (31)
#define APP_RX_BMS_DCBUSVOLTAGE                                            (32)
#define APP_RX_BMS_HIGHESTINLETTEMP                                        (33)
#define APP_RX_BMS_HIGHESTOUTLETTEMP                                       (34)
#define APP_RX_BMS_MAXBATVOLTALLOWED                                       (35)
#define APP_RX_BMS_MAXCELLTEMP                                             (36)
#define APP_RX_BMS_MAXCONTCHRGCURRENT                                      (37)
#define APP_RX_BMS_MAXCONTDISCHRGCURRENT                                   (38)
#define APP_RX_BMS_MESSAGECOUNTER_126_HEARTBEAT                            (39)
#define APP_RX_BMS_MINCELLTEMP                                             (40)
#define APP_RX_BMS_PACKCURRENT                                             (41)
#define APP_RX_BMS_PACKSTATE                                               (42)
#define APP_RX_BMS_PACKVOLTAGE                                             (43)
#define APP_RX_BMS_SOC                                                     (44)
#define APP_RX_BMS_SUBPACK10STATUS                                         (45)
#define APP_RX_BMS_SUBPACK11STATUS                                         (46)
#define APP_RX_BMS_SUBPACK12STATUS                                         (47)
#define APP_RX_BMS_SUBPACK13STATUS                                         (48)
#define APP_RX_BMS_SUBPACK14STATUS                                         (49)
#define APP_RX_BMS_SUBPACK15STATUS                                         (50)
#define APP_RX_BMS_SUBPACK16STATUS                                         (51)
#define APP_RX_BMS_SUBPACK1STATUS                                          (52)
#define APP_RX_BMS_SUBPACK2STATUS                                          (53)
#define APP_RX_BMS_SUBPACK3STATUS                                          (54)
#define APP_RX_BMS_SUBPACK4STATUS                                          (55)
#define APP_RX_BMS_SUBPACK5STATUS                                          (56)
#define APP_RX_BMS_SUBPACK6STATUS                                          (57)
#define APP_RX_BMS_SUBPACK7STATUS                                          (58)
#define APP_RX_BMS_SUBPACK8STATUS                                          (59)
#define APP_RX_BMS_SUBPACK9STATUS                                          (60)
#define APP_RX_BMS_SYSTEMISORES                                            (61)
#define APP_RX_BMS_TMAX_CELL_ID                                            (62)
#define APP_RX_BMS_TMAX_SUBPACK_ID                                         (63)
#define APP_RX_BMS_TMIN_CELL_ID                                            (64)
#define APP_RX_BMS_TMIN_SUBPACK_ID                                         (65)
#define APP_RX_BRAKE_PEDAL_POSITION                                        (66)
#define APP_RX_CHECKSUM_122                                                (67)
#define APP_RX_CHECKSUM_123                                                (68)
#define APP_RX_COMMANDMODE_MCUCMD1RES                                      (69)
#define APP_RX_CONNECTED_STRING                                            (70)
#define APP_RX_DC_LINK_VOLTAGE_VCU_RX                                      (71)
#define APP_RX_DETECTED_STRING                                             (72)
#define APP_RX_EBS_BRAKE_SWITCH                                            (73)
#define APP_RX_EBS_RED_WARNING_LAMP_STATE                                  (74)
#define APP_RX_EMERGENCYSTOP                                               (75)
#define APP_RX_EMITEMPERATURE                                              (76)
#define APP_RX_ENG_RET_SELECTION                                           (77)
#define APP_RX_FAULTDRIVECOVERWASOPENED                                    (78)
#define APP_RX_FAULTDRIVECOVERWASOPENEDSTATUS                              (79)
#define APP_RX_FAULTINTERLOCKBATTERYCABLE                                  (80)
#define APP_RX_FAULTINTERLOCKBATTERYCABLESTATUS                            (81)
#define APP_RX_FAULTINTERLOCKMOTORCABLE                                    (82)
#define APP_RX_FAULTINTERLOCKMOTORCABLESTATUS                              (83)
#define APP_RX_FAULTPHASETOCHASSIS                                         (84)
#define APP_RX_FAULTPHASETOCHASSISSTATUS                                   (85)
#define APP_RX_FAULT_CODE_EHVS_VCU_RX                                      (86)
#define APP_RX_G1GUN_LOCK_FAULT                                            (87)
#define APP_RX_G1TEMPERATURE1_FAULT                                        (88)
#define APP_RX_G1TEMPERATURE2_FAULT                                        (89)
#define APP_RX_G1TEMPERATURE_1_VAL                                         (90)
#define APP_RX_G1TEMPERATURE_2_VAL                                         (91)
#define APP_RX_G1VEHICLE_IMMOBILIZE                                        (92)
#define APP_RX_G1_GUNLOCKFEEDBACK                                          (93)
#define APP_RX_G2CHARGER_GUN_DETECTED                                      (94)
#define APP_RX_G2CHARGING_STATUS                                           (95)
#define APP_RX_G2DIFF_CURRENT_MEASURE                                      (96)
#define APP_RX_G2EVCC_READY                                                (97)
#define APP_RX_G2EVCC_STATUS_CODE                                          (98)
#define APP_RX_G2GUN_LOCK_FAULT                                            (99)
#define APP_RX_G2NEGATIVE_CONTACTOR_CONTROL                                (100)
#define APP_RX_G2POSITIVE_CONTACTOR_CONTROL                                (101)
#define APP_RX_G2TEMPERATURE1_FAULT                                        (102)
#define APP_RX_G2TEMPERATURE2_FAULT                                        (103)
#define APP_RX_G2TEMPERATURE_1_VAL                                         (104)
#define APP_RX_G2TEMPERATURE_2_VAL                                         (105)
#define APP_RX_G2VEHICLE_IMMOBILIZE                                        (106)
#define APP_RX_G2_GUNLOCKFEEDBACK                                          (107)
#define APP_RX_GEARSELECTOR_TESTSIG1                                       (108)
#define APP_RX_GEARSELECTOR_TESTSIG2                                       (109)
#define APP_RX_HALT_BRAKE_SWITCH                                           (110)
#define APP_RX_HIGHPOWERCURRENT                                            (111)
#define APP_RX_HIGHPOWERCURRENTSTATUS                                      (112)
#define APP_RX_HIGHPOWERVOLTAGE                                            (113)
#define APP_RX_HIGHPOWERVOLTAGESTATUS                                      (114)
#define APP_RX_HV_CONTACTOR_STATUS                                         (115)
#define APP_RX_MAXSAFEMOTORSPEEDFORWARD                                    (116)
#define APP_RX_MAXSAFEMOTORSPEEDFORWARDSTATUS                              (117)
#define APP_RX_MAXSAFEMOTORSPEEDREVERSE                                    (118)
#define APP_RX_MAXSAFEMOTORSPEEDREVERSESTATUS                              (119)
#define APP_RX_MCUPOLLINGVMU_BYTE1                                         (120)
#define APP_RX_MCUPOLLINGVMU_BYTE2                                         (121)
#define APP_RX_MCUPOLLINGVMU_BYTE3                                         (122)
#define APP_RX_MCUPOLLINGVMU_BYTE4                                         (123)
#define APP_RX_MCUPOLLINGVMU_BYTE5                                         (124)
#define APP_RX_MCUPOLLINGVMU_BYTE6                                         (125)
#define APP_RX_MCUPOLLINGVMU_BYTE7                                         (126)
#define APP_RX_MCUPOLLINGVMU_BYTE8                                         (127)
#define APP_RX_MCUTEMPERATURE                                              (128)
#define APP_RX_MCU_POLLING_MCU_BYTE1                                       (129)
#define APP_RX_MCU_POLLING_MCU_BYTE2                                       (130)
#define APP_RX_MCU_POLLING_MCU_BYTE3                                       (131)
#define APP_RX_MCU_POLLING_MCU_BYTE4                                       (132)
#define APP_RX_MCU_POLLING_MCU_BYTE5                                       (133)
#define APP_RX_MCU_POLLING_MCU_BYTE6                                       (134)
#define APP_RX_MCU_POLLING_MCU_BYTE7                                       (135)
#define APP_RX_MCU_POLLING_MCU_BYTE8                                       (136)
#define APP_RX_MESSAGECOUNTER_122                                          (137)
#define APP_RX_MOTORANGLE                                                  (138)
#define APP_RX_MOTORANGLESTATUS                                            (139)
#define APP_RX_MOTORSPEED                                                  (140)
#define APP_RX_MOTORSPEEDSTATUS                                            (141)
#define APP_RX_MOTORTEMPERATURE                                            (142)
#define APP_RX_MOTORTORQUEESTIMATED                                        (143)
#define APP_RX_MOTORTORQUEESTIMATEDSTATUS                                  (144)
#define APP_RX_OPERATIONALMODE_MCUCMD1RES                                  (145)
#define APP_RX_OUTPUT_CURRENT_AIRCOMP                                      (146)
#define APP_RX_OUTPUT_CURRENT_EHVS                                         (147)
#define APP_RX_PARKING_AND_OR_TRAILER_AIR_PRESS                            (148)
#define APP_RX_PNEUMATIC_SUPPLY_PRESSURE                                   (149)
#define APP_RX_PUMPCOMMUNICATIONFAULT                                      (150)
#define APP_RX_PUMPCURRENT                                                 (151)
#define APP_RX_PUMPDRYRUNFAULT                                             (152)
#define APP_RX_PUMPFAULTLEVEL                                              (153)
#define APP_RX_PUMPOVERCURRENTFAULT                                        (154)
#define APP_RX_PUMPOVERVOLTAGEFAULT                                        (155)
#define APP_RX_PUMPSPEED                                                   (156)
#define APP_RX_PUMPSTALLFAULT                                              (157)
#define APP_RX_PUMPTEMP                                                    (158)
#define APP_RX_PUMPTHERMALFAULT                                            (159)
#define APP_RX_PUMPUNDERVOLTAGEFAULT                                       (160)
#define APP_RX_PUMPVOLTAGE                                                 (161)
#define APP_RX_REGENDERATING                                               (162)
#define APP_RX_REGENDERATINGSTATUS                                         (163)
#define APP_RX_REGENTORQUEAVAIL                                            (164)
#define APP_RX_REGENTORQUEAVAILSTATUS                                      (165)
#define APP_RX_ROLLINGCOUNTER_MCUCMD1RESPONSE                              (166)
#define APP_RX_ROLLINGCOUNTER_MCUCMD2RESPONSE                              (167)
#define APP_RX_ROLLINGCOUNTER_MCUINFO1                                     (168)
#define APP_RX_ROLLINGCOUNTER_MCUINFO2                                     (169)
#define APP_RX_ROLLINGCOUNTER_MCUTHERMAL2                                  (170)
#define APP_RX_SA_OF_CTRLLINGDEVICEFORBRAKECTRL                            (171)
#define APP_RX_SERVICE_BRAKE_CIRCUIT_1_AIR_PRES                            (172)
#define APP_RX_SERVICE_BRAKE_CIRCUIT_2_AIR_PRES                            (173)
#define APP_RX_SPEEDREDUCTIONREQUEST                                       (174)
#define APP_RX_STATEMCU                                                    (175)
#define APP_RX_STATUSU0_FAULT_EHVS_VCU_RX                                  (176)
#define APP_RX_STATUSU0_OVERCURRENTFAULT_EHVS_V                            (177)
#define APP_RX_STATUSU0_WARNING_EHVS_VCU_RX                                (178)
#define APP_RX_STATUSU1_FAULT_AIRCOMP_VCU_RX                               (179)
#define APP_RX_STATUSU1_OVERCURRENT_AIRCOMP_VCU                            (180)
#define APP_RX_STATUSU1_OVERTEMP_AIRCOMP_VCU_RX                            (181)
#define APP_RX_STATUSU1_WARNING_AIRCOMP_VCU_RX                             (182)
#define APP_RX_SWITCHING_SYNC_STATUS                                       (183)
#define APP_RX_SYS_DTC                                                     (184)
#define APP_RX_T2B_BMS_WORK_MODE                                           (185)
#define APP_RX_T2B_COMP_FREQUENCY                                          (186)
#define APP_RX_T2B_COOLANT_IN_TEMP                                         (187)
#define APP_RX_T2B_COOLANT_OUT_TEMP                                        (188)
#define APP_RX_T2B_FAULT_CODE                                              (189)
#define APP_RX_T2B_MODE                                                    (190)
#define APP_RX_T2B_SIGNAL_LIFE                                             (191)
#define APP_RX_T2B_TMS_WORK_MODE                                           (192)
#define APP_RX_TRACTIONDERATING                                            (193)
#define APP_RX_TRACTIONDERATINGSTATUS                                      (194)
#define APP_RX_TRACTIONTORQUEAVAIL                                         (195)
#define APP_RX_TRACTIONTORQUEAVAILSTATUS                                   (196)
#define APP_RX_TRACTION_CTRL_OVR_SWITCH                                    (197)
#define APP_RX_TRAILER_ABS_STATUS                                          (198)
#define APP_RX_TRAILER_ABS_WARNING_SIGNAL                                  (199)
#define APP_RX_TRANSREQUEST_GEAR                                           (200)

/* Defines of Application ECU Tx Signals */
#define ECU_COM_TX_SIGNALS_NUM                                             (114)
#define APP_TX_ACKNOWLEDGEMENT                                             (0)
#define APP_TX_ANL_P48                                                     (1)
#define APP_TX_ANL_P49_24V                                                 (2)
#define APP_TX_ANL_P50_24V                                                 (3)
#define APP_TX_ANL_P65_12V                                                 (4)
#define APP_TX_ANL_P67_5V                                                  (5)
#define APP_TX_ANL_P68_5V                                                  (6)
#define APP_TX_ANL_P69_5V                                                  (7)
#define APP_TX_B2T_BATTERY_AVG_TEMP                                        (8)
#define APP_TX_B2T_BMS_WORK_MODE                                           (9)
#define APP_TX_B2T_COMP_SPEED_RESTRICTION                                  (10)
#define APP_TX_B2T_DIFFERENTIAL1                                           (11)
#define APP_TX_B2T_DIFFERENTIAL2                                           (12)
#define APP_TX_B2T_MODE                                                    (13)
#define APP_TX_B2T_SET_TARGET_TEMP                                         (14)
#define APP_TX_B2T_SIGNAL_LIFE                                             (15)
#define APP_TX_B2T_TCELL_MAX                                               (16)
#define APP_TX_B2T_TCELL_MIN                                               (17)
#define APP_TX_B2T_TMS_CONTROL_CMD                                         (18)
#define APP_TX_BOOTNUMBER                                                  (19)
#define APP_TX_CHECKSUM_200                                                (20)
#define APP_TX_COMMANDMODEEXT                                              (21)
#define APP_TX_COMMANDMODE_VMUCMD2                                         (22)
#define APP_TX_CONTROL0_EHPS                                               (23)
#define APP_TX_CONTROL1_AIRCOMP                                            (24)
#define APP_TX_DCDCONOFF                                                   (25)
#define APP_TX_EM1_ER_SEQUENCE_NUMBER                                      (26)
#define APP_TX_EM1_REF_ENG_TORQ                                            (27)
#define APP_TX_EM1_REF_RET_TORQ                                            (28)
#define APP_TX_EM1_RET_LOCATION                                            (29)
#define APP_TX_EM1_RET_TYPE                                                (30)
#define APP_TX_G1BATTERY_PACK_PRESENT_VOLT                                 (31)
#define APP_TX_G1CHARG_COMP_FLAG                                           (32)
#define APP_TX_G1EV_CONTI_CHARG_CUR_LIMIT                                  (33)
#define APP_TX_G1EV_ERROR_CODE                                             (34)
#define APP_TX_G1EV_MAX_CHARG_CUR_LIMIT                                    (35)
#define APP_TX_G1EV_READY_FLAG                                             (36)
#define APP_TX_G1NOMI_BATT_CAPA                                            (37)
#define APP_TX_G1REMAIN_BATT_CAPA                                          (38)
#define APP_TX_G1SOC                                                       (39)
#define APP_TX_G1VEHI_STOP_CHARG_FLAG                                      (40)
#define APP_TX_G2BATTERY_PACK_PRESENT_VOLT                                 (41)
#define APP_TX_G2CHARG_COMP_FLAG                                           (42)
#define APP_TX_G2EV_CONTI_CHARG_CUR_LIMIT                                  (43)
#define APP_TX_G2EV_ERROR_CODE                                             (44)
#define APP_TX_G2EV_MAX_CHARG_CUR_LIMIT                                    (45)
#define APP_TX_G2EV_READY_FLAG                                             (46)
#define APP_TX_G2NOMI_BATT_CAPA                                            (47)
#define APP_TX_G2REMAIN_BATT_CAPA                                          (48)
#define APP_TX_G2SOC                                                       (49)
#define APP_TX_G2VEHI_STOP_CHARG_FLAG                                      (50)
#define APP_TX_HOST_BMSSTATEREQUEST                                        (51)
#define APP_TX_INTERNAL_ANL_VCU_VTG                                        (52)
#define APP_TX_MAJORMCUPROTOCOL                                            (53)
#define APP_TX_MAXBATTERYVOLTAGE                                           (54)
#define APP_TX_MAXBATTERYVOLTAGESTATUS                                     (55)
#define APP_TX_MAXCHARGECURRENT                                            (56)
#define APP_TX_MAXCHARGECURRENTSTATUS                                      (57)
#define APP_TX_MAXDISCHARGECURRENT                                         (58)
#define APP_TX_MAXDISCHARGECURRENTSTATUS                                   (59)
#define APP_TX_MCUREQUESTID                                                (60)
#define APP_TX_MESSAGECOUNTER_200                                          (61)
#define APP_TX_MINBATTERYVOLTAGE                                           (62)
#define APP_TX_MINBATTERYVOLTAGESTATUS                                     (63)
#define APP_TX_MINORMCUPROTOCOL                                            (64)
#define APP_TX_OPERATIONALMODE                                             (65)
#define APP_TX_OPERATIONREQUEST_VMUCMD1                                    (66)
#define APP_TX_P07                                                         (67)
#define APP_TX_P08                                                         (68)
#define APP_TX_P11                                                         (69)
#define APP_TX_P12                                                         (70)
#define APP_TX_P13                                                         (71)
#define APP_TX_P25                                                         (72)
#define APP_TX_P27                                                         (73)
#define APP_TX_P28                                                         (74)
#define APP_TX_P29                                                         (75)
#define APP_TX_P30                                                         (76)
#define APP_TX_P32                                                         (77)
#define APP_TX_P35                                                         (78)
#define APP_TX_P36                                                         (79)
#define APP_TX_P38                                                         (80)
#define APP_TX_P52                                                         (81)
#define APP_TX_P53                                                         (82)
#define APP_TX_P54                                                         (83)
#define APP_TX_P55                                                         (84)
#define APP_TX_P61                                                         (85)
#define APP_TX_PWM_P56_DC                                                  (86)
#define APP_TX_PWM_P56_FREQ                                                (87)
#define APP_TX_PWM_P66_DC                                                  (88)
#define APP_TX_PWM_P66_FREQ                                                (89)
#define APP_TX_REBOOT_REQUEST                                              (90)
#define APP_TX_REFERENCECOMMANDMODE                                        (91)
#define APP_TX_REFERENCESPEEDCOMMAND                                       (92)
#define APP_TX_REFERENCETORQUECOMMAND                                      (93)
#define APP_TX_ROLLINGCOUNTER_VMUCMD1                                      (94)
#define APP_TX_ROLLINGCOUNTER_VMUCMD2                                      (95)
#define APP_TX_ROLLINGCOUNTER_VMUCMDSAFETY                                 (96)
#define APP_TX_SPEEDCOMMAND                                                (97)
#define APP_TX_SPEEDCOMMANDSTATUS                                          (98)
#define APP_TX_TARGETVALUE                                                 (99)
#define APP_TX_TORQUECOMMAND                                               (100)
#define APP_TX_TORQUECOMMANDSTATUS                                         (101)
#define APP_TX_TPCM_EM1_BAM                                                (102)
#define APP_TX_TPCM_EM1_BYT                                                (103)
#define APP_TX_TPCM_EM1_PGN                                                (104)
#define APP_TX_TPCM_TPDT_5THFRAME                                          (105)
#define APP_TX_TPCM_TPDT_FRAMES                                            (106)
#define APP_TX_VCU_PARALOGCOOLENTIN                                        (107)
#define APP_TX_VCU_PARALOGCOOLENTOUT                                       (108)
#define APP_TX_VCU_PARALOG_ACCPEDAL                                        (109)
#define APP_TX_VCU_PARALOG_MOTORRPM                                        (110)
#define APP_TX_VCU_PARALOG_TRQCMD                                          (111)
#define APP_TX_VCU_PARALOG_VEHSPEED                                        (112)
#define APP_TX_VMUREQUESTID                                                (113)


extern ECU_COM_strMsg_t ECU_COM_astrRx1Msg[ECU_COM_RX1_MSGS_NUM];
extern ECU_COM_strMsg_t ECU_COM_astrTx1Msg[ECU_COM_TX1_MSGS_NUM];
extern ECU_COM_strSignal_t ECU_COM_astrRx1Signal[ECU_COM_RX1_SIGNALS_NUM];
extern ECU_COM_strSignal_t ECU_COM_astrTx1Signal[ECU_COM_TX1_SIGNALS_NUM];
extern ECU_COM_strMsg_t ECU_COM_astrRx2Msg[ECU_COM_RX2_MSGS_NUM];
extern ECU_COM_strMsg_t ECU_COM_astrTx2Msg[ECU_COM_TX2_MSGS_NUM];
extern ECU_COM_strSignal_t ECU_COM_astrRx2Signal[ECU_COM_RX2_SIGNALS_NUM];
extern ECU_COM_strSignal_t ECU_COM_astrTx2Signal[ECU_COM_TX2_SIGNALS_NUM];
extern ECU_COM_strMsg_t ECU_COM_astrRx3Msg[ECU_COM_RX3_MSGS_NUM];
extern ECU_COM_strMsg_t ECU_COM_astrTx3Msg[ECU_COM_TX3_MSGS_NUM];
extern ECU_COM_strSignal_t ECU_COM_astrRx3Signal[ECU_COM_RX3_SIGNALS_NUM];
extern ECU_COM_strSignal_t ECU_COM_astrTx3Signal[ECU_COM_TX3_SIGNALS_NUM];
extern ECU_COM_strSigDecode_t ECU_COM_astrSigDecodeRx[ECU_COM_RX_SIGNALS_NUM];
extern ECU_COM_strSigDecode_t ECU_COM_astrSigDecodeTx[ECU_COM_TX_SIGNALS_NUM];


#endif /*ECU_COM_CFG_GEN_H*/


